# Generated by Django 3.1.6 on 2021-02-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_telegrambotstart'),
        ('devices', '0002_auto_20200731_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='house.location'),
        ),
    ]
