# Generated by Django 3.2 on 2021-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210620_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
    ]
