# Generated by Django 3.0.2 on 2020-01-08 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'temperature'), (1, 'light'), (2, 'motion'), (3, 'ultra sonic')])),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(editable=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.SensorInformation'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Location'),
        ),
    ]
