# Generated by Django 3.0.2 on 2020-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200108_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('bucket_name', models.CharField(max_length=60)),
                ('storage_type', models.IntegerField(choices=[(0, 'Amazon s3')])),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(0, 'Low'), (1, 'Moderate'), (2, 'High')])),
                ('created_at', models.DateTimeField(editable=False)),
                ('attachments', models.ManyToManyField(to='devices.Attachment')),
            ],
        ),
    ]
