# Generated by Django 3.0.2 on 2020-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alert_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='devices',
            field=models.ManyToManyField(blank=True, to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='devices.Attachment'),
        ),
    ]
