# Generated by Django 3.0.2 on 2020-01-21 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20200121_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
