# Generated by Django 3.0.2 on 2020-02-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_delete_alarmstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertType',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
