# Generated by Django 3.0.2 on 2020-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20200122_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='type',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
