# Generated by Django 3.2 on 2021-05-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MqttClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='The hostname or IP address of the remote broker.', max_length=100)),
                ('port', models.PositiveSmallIntegerField(default=1883, help_text='The network port of the server host to connect to.')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMqttPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('payload_json', models.JSONField()),
                ('retain', models.BooleanField(default=False)),
                ('qos', models.PositiveSmallIntegerField(default=1, help_text='The quality of service level to use.')),
                ('last_run_datetime', models.DateTimeField(blank=True, default=None, help_text='Datetime that the automation last triggered the action to run. ', null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.automation')),
                ('mqtt_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automation.mqttclient')),
            ],
        ),
    ]
