# Generated by Django 3.2 on 2021-05-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmqttpublish',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_mqtt_publish', to='automation.automation'),
        ),
    ]
