# Generated by Django 3.2 on 2021-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20210510_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmqttpublish',
            name='last_run_datetime',
            field=models.DateTimeField(blank=True, default=None, editable=False, help_text='Datetime that the automation last triggered the action to run. ', null=True),
        ),
        migrations.AlterField(
            model_name='actionmqttpublish',
            name='payload_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_name',
            field=models.CharField(choices=[('ON_MOTION_DETECTED', 'on_motion_detected')], max_length=100),
        ),
    ]
