# Generated by Django 3.2 on 2021-05-15 10:34

from django.db import migrations, models
import utils.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20210511_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_name',
            field=utils.django.models.ChoiceArrayField(base_field=models.CharField(choices=[('ON_MOTION_DETECTED', 'on_motion_detected'), ('ON_MOTION_LEFT', 'on_motion_left')], max_length=100), size=None),
        ),
    ]
