# Generated by Django 3.2 on 2021-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_automation_trigger_name'),
        ('automation', '0007_auto_20210526_1906'),
    ]

    operations = [
    ]
