# Generated by Django 3.0.7 on 2020-09-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_alarmstatus_device'),
        ('alarm', '0007_camerarectangleroi'),
    ]

    operations = [
    ]
