# Generated by Django 3.0.7 on 2020-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_merge_20200920_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerarectangleroi',
            name='device',
        ),
        migrations.AddField(
            model_name='camerarectangleroi',
            name='image_height',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerarectangleroi',
            name='image_width',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
