# Generated by Django 3.0.7 on 2020-10-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('alarm', '0014_auto_20201024_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmschedule',
            name='devices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='devices.Device'),
            preserve_default=False,
        ),
    ]
