# Generated by Django 3.0.7 on 2020-11-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('alarm', '0024_auto_20201106_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.CreateModel(
            name='CameraMotionDetectedBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=8)),
                ('y', models.DecimalField(decimal_places=4, max_digits=8)),
                ('w', models.DecimalField(decimal_places=4, max_digits=8)),
                ('h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('camera_motion_detected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm.CameraMotionDetected')),
            ],
        ),
    ]
