# Generated by Django 3.1.6 on 2021-03-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20210204_1404'),
        ('alarm', '0033_merge_20210216_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmschedule',
            name='alarm_statuses',
            field=models.ManyToManyField(help_text='List of alarm statuses to impact.', related_name='alarm_schedules', to='alarm.AlarmStatus'),
        ),
        migrations.AlterField(
            model_name='alarmschedule',
            name='end_time',
            field=models.TimeField(help_text='When the alarm should stop the monitoring and thus it will not react to anything.'),
        ),
        migrations.AlterField(
            model_name='alarmschedule',
            name='is_disabled_by_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='alarmschedule',
            name='start_time',
            field=models.TimeField(help_text='When the alarm should start to monitor if a danger is recognized to react.'),
        ),
        migrations.AlterField(
            model_name='alarmstatus',
            name='device',
            field=models.OneToOneField(help_text='The device that is controlled by the alarm status.', on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AlterField(
            model_name='alarmstatus',
            name='is_dumb',
            field=models.BooleanField(default=True, help_text='Either or not the device is dumb, which means it runs the dumb camera software. Typically used for low-end devices such as RaspberryPi zero, esp...'),
        ),
        migrations.AlterField(
            model_name='alarmstatus',
            name='running',
            field=models.BooleanField(help_text='Either or not the alarm is running on the device. If it runs, it monitor the device camera to react if a danger is recognized.'),
        ),
    ]
