# Generated by Django 3.2 on 2021-04-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_is_main'),
        ('alarm', '0035_auto_20210325_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmstatus',
            options={'verbose_name': 'alarm status', 'verbose_name_plural': 'alarm statuses'},
        ),
        migrations.AlterField(
            model_name='alarmstatus',
            name='device',
            field=models.OneToOneField(help_text='The device that is controlled by the alarm. If you do not find the desired device, it means that an alarm is already linked to it.', on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
