# Generated by Django 3.2 on 2021-08-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0036_auto_20210417_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstatus',
            name='running',
            field=models.BooleanField(default=False, help_text='Either or not the alarm is running on the device. If it runs, it monitor the device camera to react if a danger is recognized.'),
        ),
    ]
