# Generated by Django 3.2 on 2021-08-15 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('alarm', '0038_auto_20210813_0928'), ('alarm', '0039_alter_alarmscheduledaterange_turn_on_task'), ('alarm', '0040_alter_alarmscheduledaterange_datetime_end')]

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('alarm', '0037_alter_alarmstatus_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmschedule',
            name='is_disabled_by_system',
        ),
        migrations.CreateModel(
            name='AlarmScheduleDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('turn_off_task', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_schedule_date_range_off', to='django_celery_beat.periodictask')),
                ('turn_on_task', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_schedule_date_range_on', to='django_celery_beat.periodictask')),
            ],
        ),
    ]
