# Generated by Django 3.2 on 2021-08-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('alarm', '0038_auto_20210813_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmscheduledaterange',
            name='turn_on_task',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_schedule_date_range_on', to='django_celery_beat.periodictask'),
        ),
    ]
