# Generated by Django 3.0.7 on 2020-07-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=60)),
                ('sub_structure', models.CharField(max_length=60)),
            ],
            options={
                'unique_together': {('structure', 'sub_structure')},
            },
        ),
    ]
