# Generated by Django 3.0.7 on 2020-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200802_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotChatId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
            ],
        ),
    ]
