# Generated by Django 3.1.6 on 2021-02-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_delete_telegrambotchatid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user_id', 'username', 'first_name', 'last_name')},
            },
        ),
    ]
