# Generated by Django 3.0.7 on 2020-08-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_housetelegrambot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseTelegramBot',
            new_name='TelegramBot',
        ),
    ]
