# Generated by Django 3.0.7 on 2020-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_telegrambotchatid_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBotChatId',
        ),
    ]
