# Generated by Django 3.0.7 on 2021-01-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('camera', '0003_auto_20210121_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMotionDetectedPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motion_started_picture', models.ImageField(upload_to='')),
                ('motion_ended_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
    ]
