# Generated by Django 3.0.7 on 2021-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_cameramotiondetectedpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramotiondetected',
            name='motion_ended_picture',
        ),
        migrations.RemoveField(
            model_name='cameramotiondetected',
            name='motion_started_picture',
        ),
        migrations.AddField(
            model_name='cameramotiondetected',
            name='closed_by_system',
            field=models.BooleanField(default=False),
        ),
    ]
