# Generated by Django 3.1.6 on 2021-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20210124_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMotionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_records', models.PositiveIntegerField(default=0)),
                ('is_merged', models.BooleanField(default=False)),
            ],
        ),
    ]
