# Generated by Django 3.0.7 on 2020-07-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('alarm', '0002_alarmschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmschedule',
            name='turn_off_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_schedule_off', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AddField(
            model_name='alarmschedule',
            name='turn_on_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_schedule_on', to='django_celery_beat.PeriodicTask'),
        ),
    ]
