# Generated by Django 3.0.7 on 2020-08-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('alarm', '0003_auto_20200731_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMotionDetected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture_path', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
    ]
