# Generated by Django 3.0.7 on 2020-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_auto_20200731_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmScheduleDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='alarmschedule',
            name='is_disabled_by_system',
            field=models.BooleanField(default=False),
        ),
    ]
