# Generated by Django 3.0.7 on 2020-09-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_auto_20200920_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camerarectangleroi',
            old_name='image_height',
            new_name='definition_height',
        ),
        migrations.RenameField(
            model_name='camerarectangleroi',
            old_name='image_width',
            new_name='definition_width',
        ),
    ]
