# Generated by Django 3.0.7 on 2020-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0012_cameramotiondetected_in_rectangle_roi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramotiondetected',
            name='in_rectangle_roi',
        ),
        migrations.AddField(
            model_name='cameramotiondetected',
            name='in_rectangle_roi',
            field=models.ManyToManyField(blank=True, null=True, to='alarm.CameraRectangleROI'),
        ),
    ]
