# Generated by Django 3.0.7 on 2020-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0018_cameramotiondetectedpicture_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramotiondetected',
            name='event_ref',
            field=models.UUIDField(default='bdf93337-a24a-468e-b8f9-e06184672d7f', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameramotiondetectedpicture',
            name='event_ref',
            field=models.UUIDField(default='bdf93337-a24a-468e-b8f9-e06184672d7f', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
