# Generated by Django 3.0.7 on 2020-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0021_auto_20201025_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramotiondetectedpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
