# Generated by Django 3.0.7 on 2020-10-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0022_cameramotiondetectedpicture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameramotiondetectedpicture',
            name='picture_path',
        ),
    ]
