# Generated by Django 3.0.7 on 2020-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0025_auto_20201111_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerarectangleroi',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
