# Generated by Django 3.1.6 on 2021-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(auto_created=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
