# Generated by Django 3.1.6 on 2021-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepdone',
            options={'get_latest_by': 'done_at'},
        ),
        migrations.AlterField(
            model_name='stepdone',
            name='done_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
