# Generated by Django 3.0.7 on 2020-08-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('alarm', '0006_auto_20200809_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraRectangleROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=8)),
                ('y', models.DecimalField(decimal_places=4, max_digits=8)),
                ('w', models.DecimalField(decimal_places=4, max_digits=8)),
                ('h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
    ]
