# Generated by Django 3.0.7 on 2020-10-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0011_camerarectangleroi_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramotiondetected',
            name='in_rectangle_roi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alarm.CameraRectangleROI'),
        ),
    ]
