# Generated by Django 3.0.7 on 2020-10-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
        ('alarm', '0013_auto_20201004_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='cameramotiondetected',
            name='in_rectangle_roi',
            field=models.ManyToManyField(blank=True, to='alarm.CameraRectangleROI'),
        ),
    ]
