# Generated by Django 3.0.7 on 2020-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0016_auto_20201024_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmschedule',
            name='is_disabled_by_system',
            field=models.BooleanField(default=False),
        ),
    ]
