# Generated by Django 3.0.7 on 2020-12-21 17:33

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0027_auto_20201127_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmschedule',
            name='hour_end',
        ),
        migrations.RemoveField(
            model_name='alarmschedule',
            name='hour_start',
        ),
        migrations.RemoveField(
            model_name='alarmschedule',
            name='minute_end',
        ),
        migrations.RemoveField(
            model_name='alarmschedule',
            name='minute_start',
        ),
        migrations.AddField(
            model_name='alarmschedule',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmschedule',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 21, 17, 33, 48, 455343, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
