# Generated by Django 3.0.7 on 2021-01-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('alarm', '0029_auto_20210104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmschedule',
            name='turn_off_task',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_schedule_off', to='django_celery_beat.PeriodicTask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmschedule',
            name='turn_on_task',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_schedule_on', to='django_celery_beat.PeriodicTask'),
            preserve_default=False,
        ),
    ]
