# Generated by Django 3.1.6 on 2021-02-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0030_auto_20210120_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmstatus',
            name='is_dumb',
            field=models.BooleanField(default=True),
        ),
    ]
