# Generated by Django 3.1.6 on 2021-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0031_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ping',
            name='failures',
            field=models.IntegerField(default=0),
        ),
    ]
