# Generated by Django 3.1.6 on 2021-02-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0031_alarmstatus_is_dumb'),
        ('alarm', '0032_auto_20210215_1603'),
    ]

    operations = [
    ]
