# Generated by Django 3.1.6 on 2021-03-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0034_auto_20210320_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='last_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
