# Generated by Django 3.0.7 on 2021-01-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_auto_20200731_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMotionDetected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_ref', models.UUIDField()),
                ('is_motion', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='CameraROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define_picture', models.ImageField(upload_to='')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='CameraRectangleROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=8)),
                ('y', models.DecimalField(decimal_places=4, max_digits=8)),
                ('w', models.DecimalField(decimal_places=4, max_digits=8)),
                ('h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('disabled', models.BooleanField(default=False)),
                ('camera_roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.CameraROI')),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CameraMotionDetectedBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=8)),
                ('y', models.DecimalField(decimal_places=4, max_digits=8)),
                ('w', models.DecimalField(decimal_places=4, max_digits=8)),
                ('h', models.DecimalField(decimal_places=4, max_digits=8)),
                ('camera_motion_detected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.CameraMotionDetected')),
            ],
        ),
        migrations.AddField(
            model_name='cameramotiondetected',
            name='in_rectangle_roi',
            field=models.ManyToManyField(blank=True, to='camera.CameraRectangleROI'),
        ),
        migrations.CreateModel(
            name='CameraMotionDetectedPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_ref', models.UUIDField()),
                ('is_motion', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
            ],
            options={
                'unique_together': {('event_ref', 'is_motion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cameramotiondetected',
            unique_together={('event_ref', 'is_motion')},
        ),
    ]
