# Generated by Django 3.2 on 2021-04-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_is_main'),
        ('camera', '0008_auto_20210417_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameramotiondetected',
            options={'ordering': ('-motion_started_at',)},
        ),
        migrations.AddField(
            model_name='cameramotionvideo',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='camera_motions_videos', to='devices.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cameramotiondetectedpicture',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camera_motions_pictures', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='cameramotiondetectedpicture',
            name='event_ref',
            field=models.UUIDField(unique=True),
        ),
    ]
