# Generated by Django 3.2 on 2021-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_auto_20210417_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramotiondetectedboundingbox',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
