# Generated by Django 3.2 on 2021-04-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_cameramotiondetectedboundingbox_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameramotiondetectedboundingbox',
            name='h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cameramotiondetectedboundingbox',
            name='w',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cameramotiondetectedboundingbox',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cameramotiondetectedboundingbox',
            name='y',
            field=models.IntegerField(),
        ),
    ]
