# Generated by Django 3.2 on 2022-01-28 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_auto_20210430_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameramotionvideo',
            name='last_record',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
