# Generated by Django 3.0.6 on 2020-06-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=60)),
                ('sub_structure', models.CharField(max_length=60)),
            ],
            options={
                'unique_together': {('structure', 'sub_structure')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.DeviceType')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Location')),
            ],
        ),
    ]
