# Generated by Django 3.1.6 on 2021-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20210204_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
