# Generated by Django 3.0.6 on 2020-06-23 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('type', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_name', models.CharField(max_length=60)),
                ('object_name', models.CharField(max_length=100)),
                ('storage_type', models.IntegerField(choices=[(0, 'Amazon s3')])),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.AlertType')),
                ('attachments', models.ManyToManyField(blank=True, to='alerts.Attachment')),
                ('devices', models.ManyToManyField(blank=True, to='devices.Device')),
            ],
        ),
    ]
